# Generated by Django 3.0.6 on 2021-08-19 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfItems', models.IntegerField(verbose_name='numOfItems')),
                ('calcPrice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='calcPrice')),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_api.CartModel')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_api.ItemModel')),
            ],
        ),
    ]
